[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = 'nvim "%*"', block = true, for = "windows" },
]
folder = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = 'nvim "%*"', block = true, for = "windows" },
]

[open]
prepend_rules = [
	{ name = "*/", use = "folder" },
]
